### ISSUE TITLE
Example hook does not work with wildcards

### ISSUE THREAD

**Issue by bohwaz** [pawitp/acme-dns-server#1]
For a single DNS record, multiple challenges may be deployed, for example when request a certificate for "example.org *.example.org".

But the provided example hook only saves the first challenge

Here is an excerpt from my hook:

```
deploy_challenge() {
	local DOMAIN="${1}"

	echo " + Creating DNS TXT challenge for ${DOMAIN}${ACME_DNS_ALIAS:-}:"
	TARGET="$ACME_DNS_DIRECTORY/${DOMAIN}${ACME_DNS_ALIAS:-}"
	echo -n > ${TARGET}
	chmod og+r ${TARGET}

	# Manage multiple token values
	while (( "$#" >= 3 )); do
		shift # Skip domain
		shift # Skip TOKEN_FILENAME
		local TOKEN_VALUE="${1}"; shift

		echo $TOKEN_VALUE >> ${TARGET}
	done
}
```

**Comment by pawitp** [comment]
Hi. I am able to generate a certificate with multiple domains with the code in the example hook.

Do you perhaps have [HOOK_CHAIN](https://github.com/dehydrated-io/dehydrated/blob/v0.7.0/docs/hook_chain.md) enabled in your configuration?

**Comment by bohwaz** [comment]
Yes I'm using HOOK_CHAIN forgot to mention it :)

**Comment by pawitp** [comment]
As I didn't want to make the example more complicated than necessary, I'm just going to add a note that HOOK_CHAIN=yes is not supported.

**Comment by bohwaz** [comment]
Good enough for me :) Thanks.
